from typing import Any, Dict, Iterable, List, Optional, Union, overload

from pynetbox._gen import definitions
from pynetbox.core.api import Api
from pynetbox.core.app import App
from pynetbox.core.endpoint import Endpoint
from pynetbox.core.response import Record, RecordSet

class Circuit_terminationsEndpoint(Endpoint):
    def all(
        self, limit=0, offset=None
    ) -> RecordSet[definitions.CircuitTermination]: ...
    def get(
        self,
        cable_end: Optional[str] = None,
        cable_end__n: Optional[str] = None,
        cabled: Optional[bool] = None,
        circuit_id: Optional[int] = None,
        circuit_id__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        occupied: Optional[bool] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        port_speed: Optional[int] = None,
        port_speed__empty: Optional[bool] = None,
        port_speed__gt: Optional[int] = None,
        port_speed__gte: Optional[int] = None,
        port_speed__lt: Optional[int] = None,
        port_speed__lte: Optional[int] = None,
        port_speed__n: Optional[int] = None,
        provider_network_id: Optional[int] = None,
        provider_network_id__n: Optional[int] = None,
        q: Optional[str] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        term_side: Optional[str] = None,
        term_side__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        upstream_speed: Optional[int] = None,
        upstream_speed__empty: Optional[bool] = None,
        upstream_speed__gt: Optional[int] = None,
        upstream_speed__gte: Optional[int] = None,
        upstream_speed__lt: Optional[int] = None,
        upstream_speed__lte: Optional[int] = None,
        upstream_speed__n: Optional[int] = None,
        xconnect_id: Optional[str | int] = None,
        xconnect_id__empty: Optional[bool] = None,
        xconnect_id__ic: Optional[str] = None,
        xconnect_id__ie: Optional[str] = None,
        xconnect_id__iew: Optional[str] = None,
        xconnect_id__isw: Optional[str] = None,
        xconnect_id__n: Optional[str] = None,
        xconnect_id__nic: Optional[str] = None,
        xconnect_id__nie: Optional[str] = None,
        xconnect_id__niew: Optional[str] = None,
        xconnect_id__nisw: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> Optional[definitions.CircuitTermination]: ...
    def filter(
        self,
        cable_end: Optional[str] = None,
        cable_end__n: Optional[str] = None,
        cabled: Optional[bool] = None,
        circuit_id: Optional[int] = None,
        circuit_id__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        occupied: Optional[bool] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        port_speed: Optional[int] = None,
        port_speed__empty: Optional[bool] = None,
        port_speed__gt: Optional[int] = None,
        port_speed__gte: Optional[int] = None,
        port_speed__lt: Optional[int] = None,
        port_speed__lte: Optional[int] = None,
        port_speed__n: Optional[int] = None,
        provider_network_id: Optional[int] = None,
        provider_network_id__n: Optional[int] = None,
        q: Optional[str] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        term_side: Optional[str] = None,
        term_side__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        upstream_speed: Optional[int] = None,
        upstream_speed__empty: Optional[bool] = None,
        upstream_speed__gt: Optional[int] = None,
        upstream_speed__gte: Optional[int] = None,
        upstream_speed__lt: Optional[int] = None,
        upstream_speed__lte: Optional[int] = None,
        upstream_speed__n: Optional[int] = None,
        xconnect_id: Optional[str | int] = None,
        xconnect_id__empty: Optional[bool] = None,
        xconnect_id__ic: Optional[str] = None,
        xconnect_id__ie: Optional[str] = None,
        xconnect_id__iew: Optional[str] = None,
        xconnect_id__isw: Optional[str] = None,
        xconnect_id__n: Optional[str] = None,
        xconnect_id__nic: Optional[str] = None,
        xconnect_id__nie: Optional[str] = None,
        xconnect_id__niew: Optional[str] = None,
        xconnect_id__nisw: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> RecordSet[definitions.CircuitTermination]: ...
    @overload
    def create(
        self, *args: Dict[str, Any]
    ) -> definitions.CircuitTermination: ...
    @overload
    def create(
        self,
        circuit: int,
        term_side: str,
        site: Optional[int] = None,
        provider_network: Optional[int] = None,
        port_speed: Optional[int] = None,
        upstream_speed: Optional[int] = None,
        xconnect_id: Optional[str | int] = None,
        pp_info: Optional[str] = None,
        description: Optional[str] = None,
        mark_connected: Optional[bool] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
    ) -> definitions.CircuitTermination: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.CircuitTermination: ...
    def update(
        self, objects: Iterable[definitions.CircuitTermination]
    ) -> RecordSet[definitions.CircuitTermination]: ...
    def delete(
        self, objects: Iterable[definitions.CircuitTermination]
    ) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        cable_end: Optional[str] = None,
        cable_end__n: Optional[str] = None,
        cabled: Optional[bool] = None,
        circuit_id: Optional[int] = None,
        circuit_id__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        occupied: Optional[bool] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        port_speed: Optional[int] = None,
        port_speed__empty: Optional[bool] = None,
        port_speed__gt: Optional[int] = None,
        port_speed__gte: Optional[int] = None,
        port_speed__lt: Optional[int] = None,
        port_speed__lte: Optional[int] = None,
        port_speed__n: Optional[int] = None,
        provider_network_id: Optional[int] = None,
        provider_network_id__n: Optional[int] = None,
        q: Optional[str] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        term_side: Optional[str] = None,
        term_side__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        upstream_speed: Optional[int] = None,
        upstream_speed__empty: Optional[bool] = None,
        upstream_speed__gt: Optional[int] = None,
        upstream_speed__gte: Optional[int] = None,
        upstream_speed__lt: Optional[int] = None,
        upstream_speed__lte: Optional[int] = None,
        upstream_speed__n: Optional[int] = None,
        xconnect_id: Optional[str | int] = None,
        xconnect_id__empty: Optional[bool] = None,
        xconnect_id__ic: Optional[str] = None,
        xconnect_id__ie: Optional[str] = None,
        xconnect_id__iew: Optional[str] = None,
        xconnect_id__isw: Optional[str] = None,
        xconnect_id__n: Optional[str] = None,
        xconnect_id__nic: Optional[str] = None,
        xconnect_id__nie: Optional[str] = None,
        xconnect_id__niew: Optional[str] = None,
        xconnect_id__nisw: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> int: ...

class Circuit_typesEndpoint(Endpoint):
    def all(
        self, limit=0, offset=None
    ) -> RecordSet[definitions.CircuitType]: ...
    def get(
        self,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        q: Optional[str] = None,
        slug: Optional[str] = None,
        slug__empty: Optional[bool] = None,
        slug__ic: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__nie: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> Optional[definitions.CircuitType]: ...
    def filter(
        self,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        q: Optional[str] = None,
        slug: Optional[str] = None,
        slug__empty: Optional[bool] = None,
        slug__ic: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__nie: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> RecordSet[definitions.CircuitType]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.CircuitType: ...
    @overload
    def create(
        self,
        name: str,
        slug: str,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
    ) -> definitions.CircuitType: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.CircuitType: ...
    def update(
        self, objects: Iterable[definitions.CircuitType]
    ) -> RecordSet[definitions.CircuitType]: ...
    def delete(self, objects: Iterable[definitions.CircuitType]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        q: Optional[str] = None,
        slug: Optional[str] = None,
        slug__empty: Optional[bool] = None,
        slug__ic: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__nie: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> int: ...

class CircuitsEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.Circuit]: ...
    def get(
        self,
        cid: Optional[str] = None,
        cid__empty: Optional[bool] = None,
        cid__ic: Optional[str] = None,
        cid__ie: Optional[str] = None,
        cid__iew: Optional[str] = None,
        cid__isw: Optional[str] = None,
        cid__n: Optional[str] = None,
        cid__nic: Optional[str] = None,
        cid__nie: Optional[str] = None,
        cid__niew: Optional[str] = None,
        cid__nisw: Optional[str] = None,
        commit_rate: Optional[int] = None,
        commit_rate__empty: Optional[bool] = None,
        commit_rate__gt: Optional[int] = None,
        commit_rate__gte: Optional[int] = None,
        commit_rate__lt: Optional[int] = None,
        commit_rate__lte: Optional[int] = None,
        commit_rate__n: Optional[int] = None,
        contact: Optional[int] = None,
        contact__n: Optional[int] = None,
        contact_group: Optional[int] = None,
        contact_group__n: Optional[int] = None,
        contact_role: Optional[int] = None,
        contact_role__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        install_date: Optional[str] = None,
        install_date__empty: Optional[bool] = None,
        install_date__gt: Optional[str] = None,
        install_date__gte: Optional[str] = None,
        install_date__lt: Optional[str] = None,
        install_date__lte: Optional[str] = None,
        install_date__n: Optional[str] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_account_id: Optional[int] = None,
        provider_account_id__n: Optional[int] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        provider_network_id: Optional[int] = None,
        provider_network_id__n: Optional[int] = None,
        q: Optional[str] = None,
        region: Optional[int] = None,
        region__n: Optional[int] = None,
        region_id: Optional[int] = None,
        region_id__n: Optional[int] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_group: Optional[int] = None,
        site_group__n: Optional[int] = None,
        site_group_id: Optional[int] = None,
        site_group_id__n: Optional[int] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        status: Optional[str] = None,
        status__n: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        tenant: Optional[str] = None,
        tenant__n: Optional[str] = None,
        tenant_group: Optional[int] = None,
        tenant_group__n: Optional[int] = None,
        tenant_group_id: Optional[int] = None,
        tenant_group_id__n: Optional[int] = None,
        tenant_id: Optional[int] = None,
        tenant_id__n: Optional[int] = None,
        termination_date: Optional[str] = None,
        termination_date__empty: Optional[bool] = None,
        termination_date__gt: Optional[str] = None,
        termination_date__gte: Optional[str] = None,
        termination_date__lt: Optional[str] = None,
        termination_date__lte: Optional[str] = None,
        termination_date__n: Optional[str] = None,
        type: Optional[str] = None,
        type__n: Optional[str] = None,
        type_id: Optional[int] = None,
        type_id__n: Optional[int] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> Optional[definitions.Circuit]: ...
    def filter(
        self,
        cid: Optional[str] = None,
        cid__empty: Optional[bool] = None,
        cid__ic: Optional[str] = None,
        cid__ie: Optional[str] = None,
        cid__iew: Optional[str] = None,
        cid__isw: Optional[str] = None,
        cid__n: Optional[str] = None,
        cid__nic: Optional[str] = None,
        cid__nie: Optional[str] = None,
        cid__niew: Optional[str] = None,
        cid__nisw: Optional[str] = None,
        commit_rate: Optional[int] = None,
        commit_rate__empty: Optional[bool] = None,
        commit_rate__gt: Optional[int] = None,
        commit_rate__gte: Optional[int] = None,
        commit_rate__lt: Optional[int] = None,
        commit_rate__lte: Optional[int] = None,
        commit_rate__n: Optional[int] = None,
        contact: Optional[int] = None,
        contact__n: Optional[int] = None,
        contact_group: Optional[int] = None,
        contact_group__n: Optional[int] = None,
        contact_role: Optional[int] = None,
        contact_role__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        install_date: Optional[str] = None,
        install_date__empty: Optional[bool] = None,
        install_date__gt: Optional[str] = None,
        install_date__gte: Optional[str] = None,
        install_date__lt: Optional[str] = None,
        install_date__lte: Optional[str] = None,
        install_date__n: Optional[str] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_account_id: Optional[int] = None,
        provider_account_id__n: Optional[int] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        provider_network_id: Optional[int] = None,
        provider_network_id__n: Optional[int] = None,
        q: Optional[str] = None,
        region: Optional[int] = None,
        region__n: Optional[int] = None,
        region_id: Optional[int] = None,
        region_id__n: Optional[int] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_group: Optional[int] = None,
        site_group__n: Optional[int] = None,
        site_group_id: Optional[int] = None,
        site_group_id__n: Optional[int] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        status: Optional[str] = None,
        status__n: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        tenant: Optional[str] = None,
        tenant__n: Optional[str] = None,
        tenant_group: Optional[int] = None,
        tenant_group__n: Optional[int] = None,
        tenant_group_id: Optional[int] = None,
        tenant_group_id__n: Optional[int] = None,
        tenant_id: Optional[int] = None,
        tenant_id__n: Optional[int] = None,
        termination_date: Optional[str] = None,
        termination_date__empty: Optional[bool] = None,
        termination_date__gt: Optional[str] = None,
        termination_date__gte: Optional[str] = None,
        termination_date__lt: Optional[str] = None,
        termination_date__lte: Optional[str] = None,
        termination_date__n: Optional[str] = None,
        type: Optional[str] = None,
        type__n: Optional[str] = None,
        type_id: Optional[int] = None,
        type_id__n: Optional[int] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> RecordSet[definitions.Circuit]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.Circuit: ...
    @overload
    def create(
        self,
        cid: str,
        provider: int,
        type: int,
        provider_account: Optional[int] = None,
        status: Optional[str] = None,
        tenant: Optional[int] = None,
        install_date: Optional[str] = None,
        termination_date: Optional[str] = None,
        commit_rate: Optional[int] = None,
        description: Optional[str] = None,
        comments: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
    ) -> definitions.Circuit: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.Circuit: ...
    def update(
        self, objects: Iterable[definitions.Circuit]
    ) -> RecordSet[definitions.Circuit]: ...
    def delete(self, objects: Iterable[definitions.Circuit]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        cid: Optional[str] = None,
        cid__empty: Optional[bool] = None,
        cid__ic: Optional[str] = None,
        cid__ie: Optional[str] = None,
        cid__iew: Optional[str] = None,
        cid__isw: Optional[str] = None,
        cid__n: Optional[str] = None,
        cid__nic: Optional[str] = None,
        cid__nie: Optional[str] = None,
        cid__niew: Optional[str] = None,
        cid__nisw: Optional[str] = None,
        commit_rate: Optional[int] = None,
        commit_rate__empty: Optional[bool] = None,
        commit_rate__gt: Optional[int] = None,
        commit_rate__gte: Optional[int] = None,
        commit_rate__lt: Optional[int] = None,
        commit_rate__lte: Optional[int] = None,
        commit_rate__n: Optional[int] = None,
        contact: Optional[int] = None,
        contact__n: Optional[int] = None,
        contact_group: Optional[int] = None,
        contact_group__n: Optional[int] = None,
        contact_role: Optional[int] = None,
        contact_role__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        install_date: Optional[str] = None,
        install_date__empty: Optional[bool] = None,
        install_date__gt: Optional[str] = None,
        install_date__gte: Optional[str] = None,
        install_date__lt: Optional[str] = None,
        install_date__lte: Optional[str] = None,
        install_date__n: Optional[str] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_account_id: Optional[int] = None,
        provider_account_id__n: Optional[int] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        provider_network_id: Optional[int] = None,
        provider_network_id__n: Optional[int] = None,
        q: Optional[str] = None,
        region: Optional[int] = None,
        region__n: Optional[int] = None,
        region_id: Optional[int] = None,
        region_id__n: Optional[int] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_group: Optional[int] = None,
        site_group__n: Optional[int] = None,
        site_group_id: Optional[int] = None,
        site_group_id__n: Optional[int] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        status: Optional[str] = None,
        status__n: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        tenant: Optional[str] = None,
        tenant__n: Optional[str] = None,
        tenant_group: Optional[int] = None,
        tenant_group__n: Optional[int] = None,
        tenant_group_id: Optional[int] = None,
        tenant_group_id__n: Optional[int] = None,
        tenant_id: Optional[int] = None,
        tenant_id__n: Optional[int] = None,
        termination_date: Optional[str] = None,
        termination_date__empty: Optional[bool] = None,
        termination_date__gt: Optional[str] = None,
        termination_date__gte: Optional[str] = None,
        termination_date__lt: Optional[str] = None,
        termination_date__lte: Optional[str] = None,
        termination_date__n: Optional[str] = None,
        type: Optional[str] = None,
        type__n: Optional[str] = None,
        type_id: Optional[int] = None,
        type_id__n: Optional[int] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> int: ...

class Provider_accountsEndpoint(Endpoint):
    def all(
        self, limit=0, offset=None
    ) -> RecordSet[definitions.ProviderAccount]: ...
    def get(
        self,
        account: Optional[str] = None,
        account__empty: Optional[bool] = None,
        account__ic: Optional[str] = None,
        account__ie: Optional[str] = None,
        account__iew: Optional[str] = None,
        account__isw: Optional[str] = None,
        account__n: Optional[str] = None,
        account__nic: Optional[str] = None,
        account__nie: Optional[str] = None,
        account__niew: Optional[str] = None,
        account__nisw: Optional[str] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> Optional[definitions.ProviderAccount]: ...
    def filter(
        self,
        account: Optional[str] = None,
        account__empty: Optional[bool] = None,
        account__ic: Optional[str] = None,
        account__ie: Optional[str] = None,
        account__iew: Optional[str] = None,
        account__isw: Optional[str] = None,
        account__n: Optional[str] = None,
        account__nic: Optional[str] = None,
        account__nie: Optional[str] = None,
        account__niew: Optional[str] = None,
        account__nisw: Optional[str] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> RecordSet[definitions.ProviderAccount]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.ProviderAccount: ...
    @overload
    def create(
        self,
        provider: int,
        account: str,
        name: Optional[str] = None,
        description: Optional[str] = None,
        comments: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
    ) -> definitions.ProviderAccount: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.ProviderAccount: ...
    def update(
        self, objects: Iterable[definitions.ProviderAccount]
    ) -> RecordSet[definitions.ProviderAccount]: ...
    def delete(
        self, objects: Iterable[definitions.ProviderAccount]
    ) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        account: Optional[str] = None,
        account__empty: Optional[bool] = None,
        account__ic: Optional[str] = None,
        account__ie: Optional[str] = None,
        account__iew: Optional[str] = None,
        account__isw: Optional[str] = None,
        account__n: Optional[str] = None,
        account__nic: Optional[str] = None,
        account__nie: Optional[str] = None,
        account__niew: Optional[str] = None,
        account__nisw: Optional[str] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> int: ...

class Provider_networksEndpoint(Endpoint):
    def all(
        self, limit=0, offset=None
    ) -> RecordSet[definitions.ProviderNetwork]: ...
    def get(
        self,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        q: Optional[str] = None,
        service_id: Optional[str | int] = None,
        service_id__empty: Optional[bool] = None,
        service_id__ic: Optional[str] = None,
        service_id__ie: Optional[str] = None,
        service_id__iew: Optional[str] = None,
        service_id__isw: Optional[str] = None,
        service_id__n: Optional[str] = None,
        service_id__nic: Optional[str] = None,
        service_id__nie: Optional[str] = None,
        service_id__niew: Optional[str] = None,
        service_id__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> Optional[definitions.ProviderNetwork]: ...
    def filter(
        self,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        q: Optional[str] = None,
        service_id: Optional[str | int] = None,
        service_id__empty: Optional[bool] = None,
        service_id__ic: Optional[str] = None,
        service_id__ie: Optional[str] = None,
        service_id__iew: Optional[str] = None,
        service_id__isw: Optional[str] = None,
        service_id__n: Optional[str] = None,
        service_id__nic: Optional[str] = None,
        service_id__nie: Optional[str] = None,
        service_id__niew: Optional[str] = None,
        service_id__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> RecordSet[definitions.ProviderNetwork]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.ProviderNetwork: ...
    @overload
    def create(
        self,
        provider: int,
        name: str,
        service_id: Optional[str | int] = None,
        description: Optional[str] = None,
        comments: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
    ) -> definitions.ProviderNetwork: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.ProviderNetwork: ...
    def update(
        self, objects: Iterable[definitions.ProviderNetwork]
    ) -> RecordSet[definitions.ProviderNetwork]: ...
    def delete(
        self, objects: Iterable[definitions.ProviderNetwork]
    ) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        description: Optional[str] = None,
        description__empty: Optional[bool] = None,
        description__ic: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__n: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__nie: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__nisw: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        provider: Optional[str] = None,
        provider__n: Optional[str] = None,
        provider_id: Optional[int] = None,
        provider_id__n: Optional[int] = None,
        q: Optional[str] = None,
        service_id: Optional[str | int] = None,
        service_id__empty: Optional[bool] = None,
        service_id__ic: Optional[str] = None,
        service_id__ie: Optional[str] = None,
        service_id__iew: Optional[str] = None,
        service_id__isw: Optional[str] = None,
        service_id__n: Optional[str] = None,
        service_id__nic: Optional[str] = None,
        service_id__nie: Optional[str] = None,
        service_id__niew: Optional[str] = None,
        service_id__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> int: ...

class ProvidersEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.Provider]: ...
    def get(
        self,
        asn_id: Optional[int] = None,
        asn_id__n: Optional[int] = None,
        contact: Optional[int] = None,
        contact__n: Optional[int] = None,
        contact_group: Optional[int] = None,
        contact_group__n: Optional[int] = None,
        contact_role: Optional[int] = None,
        contact_role__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        q: Optional[str] = None,
        region: Optional[int] = None,
        region__n: Optional[int] = None,
        region_id: Optional[int] = None,
        region_id__n: Optional[int] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_group: Optional[int] = None,
        site_group__n: Optional[int] = None,
        site_group_id: Optional[int] = None,
        site_group_id__n: Optional[int] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        slug: Optional[str] = None,
        slug__empty: Optional[bool] = None,
        slug__ic: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__nie: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> Optional[definitions.Provider]: ...
    def filter(
        self,
        asn_id: Optional[int] = None,
        asn_id__n: Optional[int] = None,
        contact: Optional[int] = None,
        contact__n: Optional[int] = None,
        contact_group: Optional[int] = None,
        contact_group__n: Optional[int] = None,
        contact_role: Optional[int] = None,
        contact_role__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        q: Optional[str] = None,
        region: Optional[int] = None,
        region__n: Optional[int] = None,
        region_id: Optional[int] = None,
        region_id__n: Optional[int] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_group: Optional[int] = None,
        site_group__n: Optional[int] = None,
        site_group_id: Optional[int] = None,
        site_group_id__n: Optional[int] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        slug: Optional[str] = None,
        slug__empty: Optional[bool] = None,
        slug__ic: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__nie: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> RecordSet[definitions.Provider]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.Provider: ...
    @overload
    def create(
        self,
        name: str,
        slug: str,
        accounts: List[Any],
        description: Optional[str] = None,
        comments: Optional[str] = None,
        asns: Optional[List[Any]] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
    ) -> definitions.Provider: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.Provider: ...
    def update(
        self, objects: Iterable[definitions.Provider]
    ) -> RecordSet[definitions.Provider]: ...
    def delete(self, objects: Iterable[definitions.Provider]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        asn_id: Optional[int] = None,
        asn_id__n: Optional[int] = None,
        contact: Optional[int] = None,
        contact__n: Optional[int] = None,
        contact_group: Optional[int] = None,
        contact_group__n: Optional[int] = None,
        contact_role: Optional[int] = None,
        contact_role__n: Optional[int] = None,
        created: Optional[str] = None,
        created__empty: Optional[str] = None,
        created__gt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__n: Optional[str] = None,
        created_by_request: Optional[str] = None,
        id: Optional[int] = None,
        id__empty: Optional[bool] = None,
        id__gt: Optional[int] = None,
        id__gte: Optional[int] = None,
        id__lt: Optional[int] = None,
        id__lte: Optional[int] = None,
        id__n: Optional[int] = None,
        last_updated: Optional[str] = None,
        last_updated__empty: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        limit: Optional[int] = None,
        modified_by_request: Optional[str] = None,
        name: Optional[str] = None,
        name__empty: Optional[bool] = None,
        name__ic: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__n: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__nie: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__nisw: Optional[str] = None,
        offset: Optional[int] = None,
        ordering: Optional[str] = None,
        q: Optional[str] = None,
        region: Optional[int] = None,
        region__n: Optional[int] = None,
        region_id: Optional[int] = None,
        region_id__n: Optional[int] = None,
        site: Optional[str] = None,
        site__n: Optional[str] = None,
        site_group: Optional[int] = None,
        site_group__n: Optional[int] = None,
        site_group_id: Optional[int] = None,
        site_group_id__n: Optional[int] = None,
        site_id: Optional[int] = None,
        site_id__n: Optional[int] = None,
        slug: Optional[str] = None,
        slug__empty: Optional[bool] = None,
        slug__ic: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__nie: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        tag: Optional[str] = None,
        tag__n: Optional[str] = None,
        updated_by_request: Optional[str] = None,
        **kwargs: Optional[Any]
    ) -> int: ...

class CircuitsApp(App):
    def __init__(self, api: 'Api', name):
        self.circuit_terminations: Circuit_terminationsEndpoint = ...
        self.circuit_types: Circuit_typesEndpoint = ...
        self.circuits: CircuitsEndpoint = ...
        self.provider_accounts: Provider_accountsEndpoint = ...
        self.provider_networks: Provider_networksEndpoint = ...
        self.providers: ProvidersEndpoint = ...
