from typing import Any, Dict, Iterable, List, Optional, Union, overload

from pynetbox._gen import definitions
from pynetbox.core.api import Api
from pynetbox.core.app import App
from pynetbox.core.endpoint import Endpoint
from pynetbox.core.response import Record, RecordSet

class Contact_assignmentsEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.ContactAssignment]: ...
    def get(
        self,
        id: Optional[str | int] = None,
        content_type_id: Optional[str | int] = None,
        object_id: Optional[str | int] = None,
        priority: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        content_type: Optional[str] = None,
        contact_id: Optional[str | int] = None,
        role_id: Optional[str | int] = None,
        role: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        content_type_id__n: Optional[str] = None,
        object_id__n: Optional[str] = None,
        object_id__lte: Optional[str] = None,
        object_id__lt: Optional[str] = None,
        object_id__gte: Optional[str] = None,
        object_id__gt: Optional[str] = None,
        priority__n: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        content_type__n: Optional[str] = None,
        contact_id__n: Optional[str] = None,
        role_id__n: Optional[str] = None,
        role__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> Optional[definitions.ContactAssignment]: ...
    def filter(
        self,
        id: Optional[str | int] = None,
        content_type_id: Optional[str | int] = None,
        object_id: Optional[str | int] = None,
        priority: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        content_type: Optional[str] = None,
        contact_id: Optional[str | int] = None,
        role_id: Optional[str | int] = None,
        role: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        content_type_id__n: Optional[str] = None,
        object_id__n: Optional[str] = None,
        object_id__lte: Optional[str] = None,
        object_id__lt: Optional[str] = None,
        object_id__gte: Optional[str] = None,
        object_id__gt: Optional[str] = None,
        priority__n: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        content_type__n: Optional[str] = None,
        contact_id__n: Optional[str] = None,
        role_id__n: Optional[str] = None,
        role__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> RecordSet[definitions.ContactAssignment]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.ContactAssignment: ...
    @overload
    def create(
        self,
        content_type: str,
        object_id: int | int,
        contact: int,
        role: int,
        priority: str,
        id: Optional[int | int] = None,
        url: Optional[str] = None,
        display: Optional[str] = None,
        object: Optional[Any] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
    ) -> definitions.ContactAssignment: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.ContactAssignment: ...
    def update(
        self, objects: Iterable[definitions.ContactAssignment]
    ) -> RecordSet[definitions.ContactAssignment]: ...
    def delete(self, objects: Iterable[definitions.ContactAssignment]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        id: Optional[str | int] = None,
        content_type_id: Optional[str | int] = None,
        object_id: Optional[str | int] = None,
        priority: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        content_type: Optional[str] = None,
        contact_id: Optional[str | int] = None,
        role_id: Optional[str | int] = None,
        role: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        content_type_id__n: Optional[str] = None,
        object_id__n: Optional[str] = None,
        object_id__lte: Optional[str] = None,
        object_id__lt: Optional[str] = None,
        object_id__gte: Optional[str] = None,
        object_id__gt: Optional[str] = None,
        priority__n: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        content_type__n: Optional[str] = None,
        contact_id__n: Optional[str] = None,
        role_id__n: Optional[str] = None,
        role__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> int: ...

class Contact_groupsEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.ContactGroup]: ...
    def get(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        parent_id: Optional[str | int] = None,
        parent: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        parent_id__n: Optional[str] = None,
        parent__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> Optional[definitions.ContactGroup]: ...
    def filter(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        parent_id: Optional[str | int] = None,
        parent: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        parent_id__n: Optional[str] = None,
        parent__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> RecordSet[definitions.ContactGroup]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.ContactGroup: ...
    @overload
    def create(
        self,
        name: str,
        slug: str,
        parent: int,
        id: Optional[int | int] = None,
        url: Optional[str] = None,
        display: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        contact_count: Optional[int] = None,
        _depth: Optional[int] = None,
    ) -> definitions.ContactGroup: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.ContactGroup: ...
    def update(
        self, objects: Iterable[definitions.ContactGroup]
    ) -> RecordSet[definitions.ContactGroup]: ...
    def delete(self, objects: Iterable[definitions.ContactGroup]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        parent_id: Optional[str | int] = None,
        parent: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        parent_id__n: Optional[str] = None,
        parent__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> int: ...

class Contact_rolesEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.ContactRole]: ...
    def get(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> Optional[definitions.ContactRole]: ...
    def filter(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> RecordSet[definitions.ContactRole]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.ContactRole: ...
    @overload
    def create(
        self,
        name: str,
        slug: str,
        id: Optional[int | int] = None,
        url: Optional[str] = None,
        display: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
    ) -> definitions.ContactRole: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.ContactRole: ...
    def update(
        self, objects: Iterable[definitions.ContactRole]
    ) -> RecordSet[definitions.ContactRole]: ...
    def delete(self, objects: Iterable[definitions.ContactRole]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> int: ...

class ContactsEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.Contact]: ...
    def get(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        title: Optional[str] = None,
        phone: Optional[str] = None,
        email: Optional[str] = None,
        address: Optional[str] = None,
        link: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        group_id: Optional[str | int] = None,
        group: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        title__n: Optional[str] = None,
        title__ic: Optional[str] = None,
        title__nic: Optional[str] = None,
        title__iew: Optional[str] = None,
        title__niew: Optional[str] = None,
        title__isw: Optional[str] = None,
        title__nisw: Optional[str] = None,
        title__ie: Optional[str] = None,
        title__nie: Optional[str] = None,
        phone__n: Optional[str] = None,
        phone__ic: Optional[str] = None,
        phone__nic: Optional[str] = None,
        phone__iew: Optional[str] = None,
        phone__niew: Optional[str] = None,
        phone__isw: Optional[str] = None,
        phone__nisw: Optional[str] = None,
        phone__ie: Optional[str] = None,
        phone__nie: Optional[str] = None,
        email__n: Optional[str] = None,
        email__ic: Optional[str] = None,
        email__nic: Optional[str] = None,
        email__iew: Optional[str] = None,
        email__niew: Optional[str] = None,
        email__isw: Optional[str] = None,
        email__nisw: Optional[str] = None,
        email__ie: Optional[str] = None,
        email__nie: Optional[str] = None,
        address__n: Optional[str] = None,
        address__ic: Optional[str] = None,
        address__nic: Optional[str] = None,
        address__iew: Optional[str] = None,
        address__niew: Optional[str] = None,
        address__isw: Optional[str] = None,
        address__nisw: Optional[str] = None,
        address__ie: Optional[str] = None,
        address__nie: Optional[str] = None,
        link__n: Optional[str] = None,
        link__ic: Optional[str] = None,
        link__nic: Optional[str] = None,
        link__iew: Optional[str] = None,
        link__niew: Optional[str] = None,
        link__isw: Optional[str] = None,
        link__nisw: Optional[str] = None,
        link__ie: Optional[str] = None,
        link__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        group_id__n: Optional[str] = None,
        group__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> Optional[definitions.Contact]: ...
    def filter(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        title: Optional[str] = None,
        phone: Optional[str] = None,
        email: Optional[str] = None,
        address: Optional[str] = None,
        link: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        group_id: Optional[str | int] = None,
        group: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        title__n: Optional[str] = None,
        title__ic: Optional[str] = None,
        title__nic: Optional[str] = None,
        title__iew: Optional[str] = None,
        title__niew: Optional[str] = None,
        title__isw: Optional[str] = None,
        title__nisw: Optional[str] = None,
        title__ie: Optional[str] = None,
        title__nie: Optional[str] = None,
        phone__n: Optional[str] = None,
        phone__ic: Optional[str] = None,
        phone__nic: Optional[str] = None,
        phone__iew: Optional[str] = None,
        phone__niew: Optional[str] = None,
        phone__isw: Optional[str] = None,
        phone__nisw: Optional[str] = None,
        phone__ie: Optional[str] = None,
        phone__nie: Optional[str] = None,
        email__n: Optional[str] = None,
        email__ic: Optional[str] = None,
        email__nic: Optional[str] = None,
        email__iew: Optional[str] = None,
        email__niew: Optional[str] = None,
        email__isw: Optional[str] = None,
        email__nisw: Optional[str] = None,
        email__ie: Optional[str] = None,
        email__nie: Optional[str] = None,
        address__n: Optional[str] = None,
        address__ic: Optional[str] = None,
        address__nic: Optional[str] = None,
        address__iew: Optional[str] = None,
        address__niew: Optional[str] = None,
        address__isw: Optional[str] = None,
        address__nisw: Optional[str] = None,
        address__ie: Optional[str] = None,
        address__nie: Optional[str] = None,
        link__n: Optional[str] = None,
        link__ic: Optional[str] = None,
        link__nic: Optional[str] = None,
        link__iew: Optional[str] = None,
        link__niew: Optional[str] = None,
        link__isw: Optional[str] = None,
        link__nisw: Optional[str] = None,
        link__ie: Optional[str] = None,
        link__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        group_id__n: Optional[str] = None,
        group__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> RecordSet[definitions.Contact]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.Contact: ...
    @overload
    def create(
        self,
        group: int,
        name: str,
        id: Optional[int | int] = None,
        url: Optional[str] = None,
        display: Optional[str] = None,
        title: Optional[str] = None,
        phone: Optional[str] = None,
        email: Optional[str] = None,
        address: Optional[str] = None,
        link: Optional[str] = None,
        comments: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
    ) -> definitions.Contact: ...
    def create(self, *args: Dict[str, Any], **kwargs: Any) -> definitions.Contact: ...
    def update(
        self, objects: Iterable[definitions.Contact]
    ) -> RecordSet[definitions.Contact]: ...
    def delete(self, objects: Iterable[definitions.Contact]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        title: Optional[str] = None,
        phone: Optional[str] = None,
        email: Optional[str] = None,
        address: Optional[str] = None,
        link: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        group_id: Optional[str | int] = None,
        group: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        title__n: Optional[str] = None,
        title__ic: Optional[str] = None,
        title__nic: Optional[str] = None,
        title__iew: Optional[str] = None,
        title__niew: Optional[str] = None,
        title__isw: Optional[str] = None,
        title__nisw: Optional[str] = None,
        title__ie: Optional[str] = None,
        title__nie: Optional[str] = None,
        phone__n: Optional[str] = None,
        phone__ic: Optional[str] = None,
        phone__nic: Optional[str] = None,
        phone__iew: Optional[str] = None,
        phone__niew: Optional[str] = None,
        phone__isw: Optional[str] = None,
        phone__nisw: Optional[str] = None,
        phone__ie: Optional[str] = None,
        phone__nie: Optional[str] = None,
        email__n: Optional[str] = None,
        email__ic: Optional[str] = None,
        email__nic: Optional[str] = None,
        email__iew: Optional[str] = None,
        email__niew: Optional[str] = None,
        email__isw: Optional[str] = None,
        email__nisw: Optional[str] = None,
        email__ie: Optional[str] = None,
        email__nie: Optional[str] = None,
        address__n: Optional[str] = None,
        address__ic: Optional[str] = None,
        address__nic: Optional[str] = None,
        address__iew: Optional[str] = None,
        address__niew: Optional[str] = None,
        address__isw: Optional[str] = None,
        address__nisw: Optional[str] = None,
        address__ie: Optional[str] = None,
        address__nie: Optional[str] = None,
        link__n: Optional[str] = None,
        link__ic: Optional[str] = None,
        link__nic: Optional[str] = None,
        link__iew: Optional[str] = None,
        link__niew: Optional[str] = None,
        link__isw: Optional[str] = None,
        link__nisw: Optional[str] = None,
        link__ie: Optional[str] = None,
        link__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        group_id__n: Optional[str] = None,
        group__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> int: ...

class Tenant_groupsEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.TenantGroup]: ...
    def get(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        parent_id: Optional[str | int] = None,
        parent: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        parent_id__n: Optional[str] = None,
        parent__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> Optional[definitions.TenantGroup]: ...
    def filter(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        parent_id: Optional[str | int] = None,
        parent: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        parent_id__n: Optional[str] = None,
        parent__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> RecordSet[definitions.TenantGroup]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.TenantGroup: ...
    @overload
    def create(
        self,
        name: str,
        slug: str,
        id: Optional[int | int] = None,
        url: Optional[str] = None,
        display: Optional[str] = None,
        parent: Optional[int] = None,
        description: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        tenant_count: Optional[int] = None,
        _depth: Optional[int] = None,
    ) -> definitions.TenantGroup: ...
    def create(
        self, *args: Dict[str, Any], **kwargs: Any
    ) -> definitions.TenantGroup: ...
    def update(
        self, objects: Iterable[definitions.TenantGroup]
    ) -> RecordSet[definitions.TenantGroup]: ...
    def delete(self, objects: Iterable[definitions.TenantGroup]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        parent_id: Optional[str | int] = None,
        parent: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        parent_id__n: Optional[str] = None,
        parent__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> int: ...

class TenantsEndpoint(Endpoint):
    def all(self, limit=0, offset=None) -> RecordSet[definitions.Tenant]: ...
    def get(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        contact: Optional[str] = None,
        contact_role: Optional[str] = None,
        contact_group: Optional[str] = None,
        group_id: Optional[str | int] = None,
        group: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        contact__n: Optional[str] = None,
        contact_role__n: Optional[str] = None,
        contact_group__n: Optional[str] = None,
        group_id__n: Optional[str] = None,
        group__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> Optional[definitions.Tenant]: ...
    def filter(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        contact: Optional[str] = None,
        contact_role: Optional[str] = None,
        contact_group: Optional[str] = None,
        group_id: Optional[str | int] = None,
        group: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        contact__n: Optional[str] = None,
        contact_role__n: Optional[str] = None,
        contact_group__n: Optional[str] = None,
        group_id__n: Optional[str] = None,
        group__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> RecordSet[definitions.Tenant]: ...
    @overload
    def create(self, *args: Dict[str, Any]) -> definitions.Tenant: ...
    @overload
    def create(
        self,
        name: str,
        slug: str,
        id: Optional[int | int] = None,
        url: Optional[str] = None,
        display: Optional[str] = None,
        group: Optional[int] = None,
        description: Optional[str] = None,
        comments: Optional[str] = None,
        tags: Optional[List[Any]] = None,
        custom_fields: Optional[Any] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        circuit_count: Optional[int] = None,
        device_count: Optional[int] = None,
        ipaddress_count: Optional[int] = None,
        prefix_count: Optional[int] = None,
        rack_count: Optional[int] = None,
        site_count: Optional[int] = None,
        virtualmachine_count: Optional[int] = None,
        vlan_count: Optional[int] = None,
        vrf_count: Optional[int] = None,
        cluster_count: Optional[int] = None,
    ) -> definitions.Tenant: ...
    def create(self, *args: Dict[str, Any], **kwargs: Any) -> definitions.Tenant: ...
    def update(
        self, objects: Iterable[definitions.Tenant]
    ) -> RecordSet[definitions.Tenant]: ...
    def delete(self, objects: Iterable[definitions.Tenant]) -> bool: ...
    def choices(self) -> dict: ...
    def count(
        self,
        id: Optional[str | int] = None,
        name: Optional[str] = None,
        slug: Optional[str] = None,
        description: Optional[str] = None,
        created: Optional[str] = None,
        last_updated: Optional[str] = None,
        q: Optional[str] = None,
        tag: Optional[str] = None,
        contact: Optional[str] = None,
        contact_role: Optional[str] = None,
        contact_group: Optional[str] = None,
        group_id: Optional[str | int] = None,
        group: Optional[str] = None,
        id__n: Optional[str] = None,
        id__lte: Optional[str] = None,
        id__lt: Optional[str] = None,
        id__gte: Optional[str] = None,
        id__gt: Optional[str] = None,
        name__n: Optional[str] = None,
        name__ic: Optional[str] = None,
        name__nic: Optional[str] = None,
        name__iew: Optional[str] = None,
        name__niew: Optional[str] = None,
        name__isw: Optional[str] = None,
        name__nisw: Optional[str] = None,
        name__ie: Optional[str] = None,
        name__nie: Optional[str] = None,
        slug__n: Optional[str] = None,
        slug__ic: Optional[str] = None,
        slug__nic: Optional[str] = None,
        slug__iew: Optional[str] = None,
        slug__niew: Optional[str] = None,
        slug__isw: Optional[str] = None,
        slug__nisw: Optional[str] = None,
        slug__ie: Optional[str] = None,
        slug__nie: Optional[str] = None,
        description__n: Optional[str] = None,
        description__ic: Optional[str] = None,
        description__nic: Optional[str] = None,
        description__iew: Optional[str] = None,
        description__niew: Optional[str] = None,
        description__isw: Optional[str] = None,
        description__nisw: Optional[str] = None,
        description__ie: Optional[str] = None,
        description__nie: Optional[str] = None,
        created__n: Optional[str] = None,
        created__lte: Optional[str] = None,
        created__lt: Optional[str] = None,
        created__gte: Optional[str] = None,
        created__gt: Optional[str] = None,
        last_updated__n: Optional[str] = None,
        last_updated__lte: Optional[str] = None,
        last_updated__lt: Optional[str] = None,
        last_updated__gte: Optional[str] = None,
        last_updated__gt: Optional[str] = None,
        tag__n: Optional[str] = None,
        contact__n: Optional[str] = None,
        contact_role__n: Optional[str] = None,
        contact_group__n: Optional[str] = None,
        group_id__n: Optional[str] = None,
        group__n: Optional[str] = None,
        ordering: Optional[str] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
    ) -> int: ...

class TenancyApp(App):
    def __init__(self, api: "Api", name):
        self.contact_assignments: Contact_assignmentsEndpoint = ...
        self.contact_groups: Contact_groupsEndpoint = ...
        self.contact_roles: Contact_rolesEndpoint = ...
        self.contacts: ContactsEndpoint = ...
        self.tenant_groups: Tenant_groupsEndpoint = ...
        self.tenants: TenantsEndpoint = ...
