from typing import Iterable

from pynetbox.core.response import Record, RecordSet

class Endpoint:
    def __init__(self, api, app, name, model=None):
        self.name = name.replace("_", "-")
        self.api = api
        self.base_url = api.base_url
        self.token = api.token
        self.session_key = api.session_key
        self.url: str
    def all(self, limit=0, offset=None) -> RecordSet: ...
    def get(self, *args, **kwargs) -> Record: ...
    def filter(self, *args, **kwargs) -> RecordSet: ...
    def create(self, *args, **kwargs) -> Record: ...
    def update(self, objects: Iterable[Record]) -> RecordSet: ...
    def delete(self, objects: Iterable[Record]): ...
    def choices(self) -> dict: ...
    def count(self, *args, **kwargs) -> int: ...
